### ISSUE TITLE
CommandInvoker Question

### ISSUE THREAD

**Issue by mmoore99** [robashton/RavenGallery#6]
Rob, I have a question regarding your use of CommandInvoker's to do processing after receiving a post.  How would you handle the situation where the method in the controller that calls the CommandInvoker needs some output from the handler that the CommandInvoker calls in order to refresh the view to send back to the client?  For example, let's say the handler will update some number of objects based on the input from the post and the controller needs to know what objects have been updated before refreshing the view.

**Comment by robashton** [comment]
Avoid needing to do that for the most part - requirements can always be adjusted to avoid the necessity for it.

In that situation I'd probably just bypass the command system rather than try to come up with an elaborate framework for it.
